package main

import (
	"ascii-art-web/pkg/generator"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// TestErrorHandler() simulates conditions where
// errorHandler() is called in homeHandler()
func TestErrorHandler(t *testing.T) {
	testCases := []struct {
		method         string
		url            string
		formData       string
		expectedText   string
		expectedStatus int
	}{
		{
			// invalid URL
			method:         "GET",
			url:            "/asc11-a47",
			formData:       "",
			expectedText:   "404 page not found",
			expectedStatus: 404,
		}, {
			// incorrect banner style name
			method:         "POST",
			url:            "/",
			formData:       "text=hey&banner=sun",
			expectedText:   "internal server error",
			expectedStatus: 500,
		}, {
			// empty text input
			method:         "POST",
			url:            "/",
			formData:       "text=&banner=shadow",
			expectedText:   "400 bad request",
			expectedStatus: 400,
		},
		{
			// invalid request to /
			method:         "HEAD",
			url:            "/",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
		{
			// invalid request to /ascii-art
			method:         "PUT",
			url:            "/ascii-art",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
		{
			// invalid request to /
			method:         "DELETE",
			url:            "/",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
		{
			// invalid request to /
			method:         "CONNECT",
			url:            "/",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
		{
			// invalid request to /
			method:         "OPTIONS",
			url:            "/",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
		{
			// invalid request to /
			method:         "TRACE",
			url:            "/",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
		{
			// invalid request to /
			method:         "PATCH",
			url:            "/",
			expectedText:   "405 method not allowed",
			expectedStatus: 405,
		},
	}

	for _, tc := range testCases {
		generator.GetStyles()
		req, err := http.NewRequest(tc.method, tc.url, strings.NewReader(tc.formData))
		if err != nil {
			t.Fatal(err)
		}
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		respRec := httptest.NewRecorder()
		handler := http.HandlerFunc(homeHandler)
		handler.ServeHTTP(respRec, req)

		if status := respRec.Code; status != tc.expectedStatus {
			t.Errorf("Expected HTTP Status Code %v got %v.", tc.expectedStatus, status)
		}
		if !strings.Contains(respRec.Body.String(), tc.expectedText) {
			t.Errorf("Expected content not found. %s", tc.expectedText)
		}
	}
}

func TestGetFormInput(t *testing.T) {
	testCases := []struct {
		formData       string
		expectedText   string
		expectedBanner string
		expectedError  string
	}{
		{
			// valid case
			formData:       "text=hello&banner=shadow",
			expectedText:   "hello",
			expectedBanner: "shadow",
			expectedError:  "",
		},
		{
			// missing text
			formData:       "banner=shadow",
			expectedText:   "",
			expectedBanner: "",
			expectedError:  "400",
		},
		{
			// missing banner.
			// unlikely scenario as standard should be define by dafualt
			formData:       "text=hello",
			expectedText:   "",
			expectedBanner: "",
			expectedError:  "400",
		},
	}
	for _, tc := range testCases {
		req, err := http.NewRequest("POST", "/", strings.NewReader(tc.formData))
		if err != nil {
			t.Fatal(err)
		}

		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		text, banner, errForm := getFormInputs(req)

		if text != tc.expectedText ||
			banner != tc.expectedBanner ||
			errForm != tc.expectedError {
			t.Errorf("Failed reading form: %s", tc.formData)
		}

	}
}

// TestHomeHandlerGet() test the valid GET request to homeHandler
func TestHomeHandlerGet(t *testing.T) {
	req, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	respRec := httptest.NewRecorder()
	handler := http.HandlerFunc(homeHandler)
	handler.ServeHTTP(respRec, req)

	if status := respRec.Code; status != http.StatusOK {
		t.Errorf("Expected HTTP Status Code 200.")
	}
	if !strings.Contains(respRec.Body.String(), "Enter text\r\nhere") &&
		!strings.Contains(respRec.Body.String(), "Enter text\nhere") {
		t.Errorf("Expected content not found.")
	}
}

// TestHomeHandlerPost() test valid POST request to homeHandler().
// It test the different error messages generated by GenArt().
func TestHomeHandlerPost(t *testing.T) {
	testCases := []struct {
		formData       string
		expectedText   string
		expectedStatus int
	}{
		{
			formData: "text=hello&banner=standard",
			expectedText: ` _              _   _          
| |            | | | |         
| |__     ___  | | | |   ___   
|  _ \   / _ \ | | | |  / _ \  
| | | | |  __/ | | | | | (_) | 
|_| |_|  \___| |_| |_|  \___/  
                               `,
			expectedStatus: 200,
		},
		{
			formData: "text=\n\nhello There\n\nAuditor!&banner=shadow",
			expectedText: `                                                                                      
_|                _| _|                _|_|_|_|_| _|                                  
_|_|_|     _|_|   _| _|   _|_|             _|     _|_|_|     _|_|   _|  _|_|   _|_|   
_|    _| _|_|_|_| _| _| _|    _|           _|     _|    _| _|_|_|_| _|_|     _|_|_|_| 
_|    _| _|       _| _| _|    _|           _|     _|    _| _|       _|       _|       
_|    _|   _|_|_| _| _|   _|_|             _|     _|    _|   _|_|_| _|         _|_|_| 
                                                                                      
                                                                                      

                                                            
  _|_|                  _| _|   _|                       _| 
_|    _| _|    _|   _|_|_|    _|_|_|_|   _|_|   _|  _|_| _| 
_|_|_|_| _|    _| _|    _| _|   _|     _|    _| _|_|     _| 
_|    _| _|    _| _|    _| _|   _|     _|    _| _|          
_|    _|   _|_|_|   _|_|_| _|     _|_|   _|_|   _|       _| 
                                                            
                                                            `,
			expectedStatus: 200,
		},
		{
			formData:       "text=äöå&banner=standard",
			expectedText:   `character not a printable ASCII char: ä`,
			expectedStatus: 200,
		},
		{
			formData:       "text=\n\n\n&banner=standard",
			expectedText:   `no character to convert`,
			expectedStatus: 200,
		},
	}
	for _, tc := range testCases {
		req, err := http.NewRequest("POST", "/ascii-art", strings.NewReader(tc.formData))
		if err != nil {
			t.Fatal(err)
		}
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
		respRec := httptest.NewRecorder()
		handler := http.HandlerFunc(homeHandler)
		handler.ServeHTTP(respRec, req)

		if status := respRec.Code; status != tc.expectedStatus {
			t.Errorf("Expected HTTP Status Code %v got %v.", tc.expectedStatus, status)
		}
		if !strings.Contains(respRec.Body.String(), tc.expectedText) {
			t.Errorf("Expected content not found. %s", tc.expectedText)
		}
	}
}
